name: Container registry

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/isen-python:latest,${{ vars.DOCKERHUB_USERNAME }}/isen-python:${{ github.sha }}

  trivy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Set up Trivy
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          cache: true
          version: latest

      - name: Run Trivy vulnerability scanner on Docker image
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ vars.DOCKERHUB_USERNAME }}/isen-python:latest'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          skip-setup-trivy: true

  sbom:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0
        with:
          image: '${{ vars.DOCKERHUB_USERNAME }}/isen-python:latest'
          format: 'spdx-json'
          output-file: 'sbom.spdx.json'

      - name: Scan SBOM with Grype
        continue-on-error: true
        uses: anchore/scan-action@v6
        with:
          sbom: 'sbom.spdx.json'
          output-format: 'sarif'
          output-file: 'grype-results.sarif'

      - name: Upload Grype results
        uses: actions/upload-artifact@v4
        with:
          name: grype-results
          path: grype-results.sarif

  google:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'  # Your service account key JSON stored as a GitHub secret

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet
      
      - name: Build and push to Google Artifact Registry
        run: |
          docker build -t europe-west1-docker.pkg.dev/gen-lang-client-0759069195/isen-python/isen-python:latest .
          docker push europe-west1-docker.pkg.dev/gen-lang-client-0759069195/isen-python/isen-python:latest

  deploy:
    needs: google
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'hello-cloud-run' 
          image: 'europe-west1-docker.pkg.dev/gen-lang-client-0759069195/isen-python/isen-python:latest'
          region: 'europe-west1'
          project_id: 'gen-lang-client-0759069195'  # AJOUTÉ ICI

      - name: Use output
        run: 'curl "${{ steps.deploy.outputs.url }}"'


