name: Bandit and ZAP

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: bandit
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          pip install -r requirements.txt

      - name: Run tests with bandit
        run: |
          bandit -r . -x "./integration_tests/","./unit_tests/"

  zap_scan:
    runs-on: ubuntu-latest
    env:
        PRODUCTION_KEY: ${{secrets.PRODUCTION_KEY}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Start Django server
        run: |
          python3 manage.py runserver 127.0.0.1:8080 &
          sleep 10  # Give server time to start


      - name: Run ZAP security scan with zap-baseline-scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Ajout du token
          target: 'http://localhost:8080'     # Change avec l'URL de ton app
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Upload ZAP report to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: './zap_report.html'
