name: Bandit and ZAP

on:
  push:
    branches:
      - main  # Exécution uniquement sur la branche par défaut

jobs:
  tests:
    runs-on: ubuntu-latest
    name: bandit
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          pip install -r requirements.txt

      - name: Run tests with bandit
        run: |
          bandit -r . -x "./integration_tests/","./unit_tests/"

  zap_scan:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Vérification supplémentaire pour la branche par défaut
    env:
        PRODUCTION_KEY: ${{secrets.PRODUCTION_KEY}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and run application with Docker
        run: |
          docker build -t my-django-app .
          docker run -d -p 8080:8080 --name app-container my-django-app
          sleep 15  # Attendre que l'application démarre

      - name: Check if application is running
        run: |
          curl -s --retry 5 --retry-delay 5 --retry-connrefused http://localhost:8080/ || echo "Application is starting, continuing..."

      - name: Run ZAP security scan with zap-baseline-scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:8080'
          rules_file_name: '.zap/rules.tsv'
          fail_action: false  # Ne pas faire échouer le workflow si le scan trouve des problèmes
          allow_issue_writing: false
          cmd_options: '-J zap-report.json -I'  # Générer un rapport JSON avec l'option -J

      - name: Upload ZAP JSON report to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: zap-json-report
          path: './zap-report.json'

      - name: Upload ZAP baseline report to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: zap-baseline-report
          path: './zap-baseline*'