name: Bandit and ZAP

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: bandit
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          pip install -r requirements.txt

      - name: Run tests with bandit
        run: |
          bandit -r . -x "./integration_tests/","./unit_tests/"

  zap_scan:
    runs-on: ubuntu-latest
    needs: tests
    name: ZAP security scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ZAP Docker container
        run: |
          docker pull owasp/zap2docker-stable

      - name: Run ZAP security scan
        run: |
          docker run -u zap -v $PWD:/zap/wrk:rw owasp/zap2docker-stable zap-baseline.py -t http://localhost:8080 -g gen.conf -r zap_report.html

      - name: Upload ZAP report to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: zap_report.html
